actors:
  alice:
    image_url: /images/actors/nhgc.jpg
    name: nhgc
    url: https://twitter.com/n_hgc36
  bob:
    image_url: /images/actors/shimmei.jpg
    name: shimmei
    url: https://twitter.com/Sony_Shimmei
author: nhgc
description: OSYABERI BOOKSの活動や読んだ本、輪読会のまとめなどをゆるく発信しています。
description_long: OSYABERI BOOKSは、サラリーマン・博士・AIエンジニアなど様々なバックグラウンドの人がテーマに沿って本（または他のメディア）を読み、ゆるくおしゃべりするコミュニティ
email: nhgc36@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: OBbooks
itunes_podcast_url:
keywords: books,輪読,読書,コミュニティ
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: OSYABERI BOOKS
url: http://example.com
